apiVersion: v1

kind: Service

metadata:

  name: vprofile-service

  labels:

    app: vprofile

spec:

  selector:

    app: vprofile
 
  ports:

    - port: 8080

      targetPort: 8080
 
  type: LoadBalancer
