apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vprofile
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: vprofile
  targetNamespace: default
